# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-17 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auto_user_provision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotatingprovisionkey',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotatingprovisionkey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='rotatingprovisionkey',
            name='rotation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotatingprovisionkey',
            name='rotation_period',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
